document.addEventListener("DOMContentLoaded", () => {
    const yearElement = document.getElementById("year");
    const currentYear = new Date().getFullYear();
    yearElement.textContent = currentYear;
});

const quotes = [
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "If life were predictable it would cease to be life, and be without flavor. - Eleanor Roosevelt",
    "If you look at what you have in life, you'll always have more. - Oprah Winfrey",
    "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success. - James Cameron",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "Spread love everywhere you go. Let no one ever come to you without leaving happier. - Mother Teresa",
    "When you reach the end of your rope, tie a knot in it and hang on. - Franklin D. Roosevelt",
    "Always remember that you are absolutely unique. Just like everyone else. - Margaret Mead",
    "Don't judge each day by the harvest you reap but by the seeds that you plant. - Robert Louis Stevenson",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Tell me and I forget. Teach me and I remember. Involve me and I learn. - Benjamin Franklin",
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. - Helen Keller",
    "It is during our darkest moments that we must focus to see the light. - Aristotle",
    "Whoever is happy will make others happy too. - Anne Frank",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    "You will face many defeats in life, but never let yourself be defeated. - Maya Angelou",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "If life were predictable it would cease to be life, and be without flavor. - Eleanor Roosevelt",
    "If you look at what you have in life, you'll always have more. - Oprah Winfrey",
    "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success. - James Cameron",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "The purpose of our lives is to be happy. - Dalai Lama",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "Get busy living or get busy dying. - Stephen King",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "Many of life's failures are people who did not realize how close they were to success when they gave up. - Thomas A. Edison",
    "If you want to live a happy life, tie it to a goal, not to people or things. - Albert Einstein",
    "Never let the fear of striking out keep you from playing the game. - Babe Ruth",
    "Money and success don’t change people; they merely amplify what is already there. - Will Smith",
    "Your time is limited, don’t waste it living someone else’s life. Don’t be trapped by dogma – which is living with the results of other people’s thinking. - Steve Jobs",
    "Not how long, but how well you have lived is the main thing. - Seneca",
    "If life were predictable it would cease to be life, and be without flavor. - Eleanor Roosevelt",
    "The whole secret of a successful life is to find out what is one’s destiny to do, and then do it. - Henry Ford",
    "In order to write about life first you must live it. - Ernest Hemingway",
    "The big lesson in life, baby, is never be scared of anyone or anything. - Frank Sinatra",
    "Sing like no one’s listening, love like you’ve never been hurt, dance like nobody’s watching, and live like it’s heaven on earth. - Mark Twain",
    "Curiosity about life in all of its aspects, I think, is still the secret of great creative people. - Leo Burnett",
    "Life is not a problem to be solved, but a reality to be experienced. - Soren Kierkegaard",
    "The unexamined life is not worth living. - Socrates",
    "Turn your wounds into wisdom. - Oprah Winfrey",
    "The way I see it, if you want the rainbow, you gotta put up with the rain. - Dolly Parton",
    "Do all the good you can, for all the people you can, in all the ways you can, as long as you can. - Hillary Clinton",
    "Don’t settle for what life gives you; make life better and build something. - Ashton Kutcher",
    "Everybody wants to be famous, but nobody wants to do the work. I live by that. You grind hard so you can play hard. At the end of the day, you put all the work in, and eventually it’ll pay off. It could be in a year, it could be in 30 years. Eventually, your hard work will pay off. - Kevin Hart",
    "Everything negative – pressure, challenges – is all an opportunity for me to rise. - Kobe Bryant",
    "I like criticism. It makes you strong. - LeBron James",
    "You never really learn much from hearing yourself speak. - George Clooney",
    "Life imposes things on you that you can’t control, but you still have the choice of how you’re going to live through this. - Celine Dion",
    "Life is never easy. There is work to be done and obligations to be met – obligations to truth, to justice, and to liberty. - John F. Kennedy",
    "Live for each second without hesitation. - Elton John",
    "Life is really simple, but we insist on making it complicated. - Confucius",
    "Life is a succession of lessons which must be lived to be understood. - Ralph Waldo Emerson",
    "My mama always said, life is like a box of chocolates. You never know what you’re gonna get. - Forrest Gump",
    "Watch your thoughts; they become words. Watch your words; they become actions. Watch your actions; they become habits. Watch your habits; they become character. Watch your character; it becomes your destiny. - Lao-Tze",
    "When we do the best we can, we never know what miracle is wrought in our life or the life of another. - Helen Keller",
    "The healthiest response to life is joy. - Deepak Chopra",
    "Life is like riding a bicycle. To keep your balance, you must keep moving. - Albert Einstein",
    "Life is really simple, but men insist on making it complicated. - Confucius",
    "Life is a succession of lessons which must be lived to be understood. - Ralph Waldo Emerson",
    "My mama always said, life is like a box of chocolates. You never know what you’re gonna get. - Forrest Gump",
    "Watch your thoughts; they become words. Watch your words; they become actions. Watch your actions; they become habits. Watch your habits; they become character. Watch your character; it becomes your destiny. - Lao-Tze",
    "When we do the best we can, we never know what miracle is wrought in our life or the life of another. - Helen Keller",
    "The healthiest response to life is joy. - Deepak Chopra",
    "Life is like riding a bicycle. To keep your balance, you must keep moving. - Albert Einstein",
    "Keep smiling, because life is a beautiful thing and there's so much to smile about. - Marilyn Monroe",
    "The greatest pleasure of life is love. - Euripides",
    "Life is what we make it, always has been, always will be. - Grandma Moses",
    "Life's tragedy is that we get old too soon and wise too late. - Benjamin Franklin",
    "Life is about making an impact, not making an income. - Kevin Kruse",
    "I've failed over and over and over again in my life and that is why I succeed. - Michael Jordan",
    "The purpose of our lives is to be happy. - Dalai Lama",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "Get busy living or get busy dying. - Stephen King",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "Many of life's failures are people who did not realize how close they were to success when they gave up. - Thomas A. Edison",
    "If you want to live a happy life, tie it to a goal, not to people or things. - Albert Einstein",
    "Never let the fear of striking out keep you from playing the game. - Babe Ruth",
    "Money and success don’t change people; they merely amplify what is already there. - Will Smith",

]

function generateQuote() {
    const quoteElement = document.getElementById("quote");
    const randomIndex = Math.floor(Math.random() * quotes.length);
    quoteElement.textContent = quotes[randomIndex];
}
